package br.com.mercado.view;

import br.com.mercado.control.TelaPrincipalControl;

/**
 *
 * @author William
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    TelaPrincipalControl telaPrincipalControl;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        telaPrincipalControl = new TelaPrincipalControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemGerenciarCliente = new javax.swing.JMenuItem();
        menuItemVenda = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemGerenciarProduto = new javax.swing.JMenuItem();
        menuItemGerenciarCategoria = new javax.swing.JMenuItem();
        menuItemEntradaProduto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemGerenciarFornecedor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemGerenciarFuncionario = new javax.swing.JMenuItem();
        menuItemGerenciarTipoUsuario = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemReceita = new javax.swing.JMenuItem();
        menuItemDespesa = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuItemAjuda = new javax.swing.JMenuItem();
        menuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        desktopPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        desktopPane.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 193, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mercado");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/clientes_32x32.png"))); // NOI18N
        jMenu1.setText("Clientes");

        menuItemGerenciarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/gerenciar_32x32.png"))); // NOI18N
        menuItemGerenciarCliente.setText("Gerenciar");
        menuItemGerenciarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGerenciarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemGerenciarCliente);

        menuItemVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/venda_32x32.png"))); // NOI18N
        menuItemVenda.setText("Venda");
        menuItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVendaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemVenda);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/produto_32x32.png"))); // NOI18N
        jMenu4.setText("Produtos");

        menuItemGerenciarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/gerenciar_32x32.png"))); // NOI18N
        menuItemGerenciarProduto.setText("Gerenciar");
        menuItemGerenciarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGerenciarProdutoActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemGerenciarProduto);

        menuItemGerenciarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/categoria_32x32.png"))); // NOI18N
        menuItemGerenciarCategoria.setText("Categoria");
        menuItemGerenciarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGerenciarCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemGerenciarCategoria);

        menuItemEntradaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/down_32x32.png"))); // NOI18N
        menuItemEntradaProduto.setText("Entrada");
        menuItemEntradaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEntradaProdutoActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemEntradaProduto);

        jMenuBar1.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/truck_32x32.png"))); // NOI18N
        jMenu3.setText("Fornecedores");

        menuItemGerenciarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/gerenciar_32x32.png"))); // NOI18N
        menuItemGerenciarFornecedor.setText("Gerenciar");
        menuItemGerenciarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGerenciarFornecedorActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemGerenciarFornecedor);

        jMenuBar1.add(jMenu3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/people_32x32.png"))); // NOI18N
        jMenu2.setText("Funcionarios");

        menuItemGerenciarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/gerenciar_32x32.png"))); // NOI18N
        menuItemGerenciarFuncionario.setText("Gerenciar");
        menuItemGerenciarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGerenciarFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemGerenciarFuncionario);

        menuItemGerenciarTipoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/cardUser_32x32.png"))); // NOI18N
        menuItemGerenciarTipoUsuario.setText("Tipo de Usuário");
        menuItemGerenciarTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGerenciarTipoUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemGerenciarTipoUsuario);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/money_32x32.png"))); // NOI18N
        jMenu5.setText("Financeiro");

        menuItemReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/receita_32x32.png"))); // NOI18N
        menuItemReceita.setText("Receitas");
        menuItemReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReceitaActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemReceita);

        menuItemDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/despesa_32x32.png"))); // NOI18N
        menuItemDespesa.setText("Despesas");
        menuItemDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDespesaActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemDespesa);

        jMenuBar1.add(jMenu5);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/info_32x32.png"))); // NOI18N
        jMenu7.setText("Sobre");

        menuItemAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/ajuda_32x32.png"))); // NOI18N
        menuItemAjuda.setText("Ajuda");
        jMenu7.add(menuItemAjuda);

        menuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercado/img/developer_32x32.png"))); // NOI18N
        menuItemSobre.setText("Sobre");
        menuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSobreActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemSobre);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemGerenciarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGerenciarFuncionarioActionPerformed
       telaPrincipalControl.chamarTelaGerenciarFuncionarioAction();
    }//GEN-LAST:event_menuItemGerenciarFuncionarioActionPerformed

    private void menuItemGerenciarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGerenciarProdutoActionPerformed
        telaPrincipalControl.chamarTelaProdutoGerenciarAction();
    }//GEN-LAST:event_menuItemGerenciarProdutoActionPerformed

    private void menuItemEntradaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEntradaProdutoActionPerformed
        telaPrincipalControl.chamarTelaEntradaProdutoGerenciarAction();
    }//GEN-LAST:event_menuItemEntradaProdutoActionPerformed

    private void menuItemGerenciarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGerenciarCategoriaActionPerformed
        telaPrincipalControl.chamarTelaCategoriaGerenciarAction();
    }//GEN-LAST:event_menuItemGerenciarCategoriaActionPerformed

    private void menuItemGerenciarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGerenciarClienteActionPerformed
        telaPrincipalControl.chamarTelaClienteGerenciarAction();
    }//GEN-LAST:event_menuItemGerenciarClienteActionPerformed

    private void menuItemGerenciarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGerenciarFornecedorActionPerformed
        telaPrincipalControl.chamarTelaFornecedorGerenciarAction();
    }//GEN-LAST:event_menuItemGerenciarFornecedorActionPerformed

    private void menuItemGerenciarTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGerenciarTipoUsuarioActionPerformed
        telaPrincipalControl.chamarTelaTipoUsuarioGerenciarAction();
    }//GEN-LAST:event_menuItemGerenciarTipoUsuarioActionPerformed

    private void menuItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendaActionPerformed
        telaPrincipalControl.chamarTelaVendaAction();
    }//GEN-LAST:event_menuItemVendaActionPerformed

    private void menuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSobreActionPerformed
        // TODO add your handling code here:
        telaPrincipalControl.chamarTelaSobreAction();
    }//GEN-LAST:event_menuItemSobreActionPerformed

    private void menuItemReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReceitaActionPerformed
        // TODO add your handling code here:
        telaPrincipalControl.chamarTelaReceitaGerenciarAction();
        
    }//GEN-LAST:event_menuItemReceitaActionPerformed

    private void menuItemDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDespesaActionPerformed
        // TODO add your handling code here:
        telaPrincipalControl.chamarTelaDespesaGerenciarAction();
    }//GEN-LAST:event_menuItemDespesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JDesktopPane desktopPane = new javax.swing.JDesktopPane();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemAjuda;
    private javax.swing.JMenuItem menuItemDespesa;
    private javax.swing.JMenuItem menuItemEntradaProduto;
    private javax.swing.JMenuItem menuItemGerenciarCategoria;
    private javax.swing.JMenuItem menuItemGerenciarCliente;
    private javax.swing.JMenuItem menuItemGerenciarFornecedor;
    private javax.swing.JMenuItem menuItemGerenciarFuncionario;
    private javax.swing.JMenuItem menuItemGerenciarProduto;
    private javax.swing.JMenuItem menuItemGerenciarTipoUsuario;
    private javax.swing.JMenuItem menuItemReceita;
    private javax.swing.JMenuItem menuItemSobre;
    private javax.swing.JMenuItem menuItemVenda;
    // End of variables declaration//GEN-END:variables
}
